require_relative "./lotto_cli_gem/version"
require_relative "./lotto_cli_gem/game"
require_relative "./lotto_cli_gem/CLI"
require_relative "./lotto_cli_gem/user"
require_relative "./lotto_cli_gem/scraper"
require_relative "./lotto_cli_gem/ticket"
require_relative "./lotto_cli_gem/user"